[package]
name = "rulez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evalexpr = "8.1.0"
elsa = "1.8.0"

[[bin]]
name = "rulez"
path = "lib.rs"
